import = [
  "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
decorations = "Buttonless"
# decorations = "Transparent"
dimensions = { columns = 200, lines = 50 }
position = { x = 370, y = 184 }
padding = {x = 5, y = 5}
opacity = 1
blur = false
option_as_alt = "Both" # (macos only)

[font]
normal = { family = "CaskaydiaCove Nerd Font Mono", style = "Regular" }
size = 12

[keyboard]
bindings = [
  # { key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
]



