import = [
  "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
dimensions = { columns = 200, lines = 70 }
position = { x = 20, y = 60 }
padding = {x = 5, y = 5}
opacity = 0.98



